apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-nginx-script
  namespace: k6-tests-nginx
data:
  load_test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '2m', target: 50 },
        { duration: '2m', target: 100 },
        { duration: '8m', target: 200 },
        { duration: '2m', target: 100 },
        { duration: '1m', target: 0 },
      ],
    };

    export default function () {
      let res = http.get('http://nipa.sudlor.me/');

      check(res, {
        'status is 200': (r) => r.status === 200,
      });

      sleep(0.5);
    }
