apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-test-apisix
  namespace: k6-tests-apisix
spec:
  parallelism: 3
  arguments: "--out json=/dev/stdout"
  runner:
    env:
      - name: K6_NO_SETUP_TEARDOWN
        value: "true"
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
  script:
    configMap:
      name: k6-apisix-script
      file: load_test.js

