apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-test-nginx
  namespace: k6-tests-nginx
spec:
  parallelism: 3                      # จำนวน pod ที่ใช้รัน
  script:
    configMap:
      name: k6-nginx-script           # ต้องตรงกับ configMap ที่เราสร้าง
      file: load_test.js
  arguments: "--out json=/tests/output.json"
  runner:
    env:
      - name: K6_NO_SETUP_TEARDOWN
        value: "true"
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
